# Generated by Django 4.0.6 on 2022-07-22 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('producer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Producer')),
                ('ingredient', models.CharField(blank=True, max_length=50, null=True, verbose_name='Wirkstoff')),
                ('package', models.PositiveIntegerField(help_text=' Tablette(n)', verbose_name='Packungsgröße')),
                ('strength', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Strength')),
                ('unit', models.CharField(choices=[('mg', 'Milligramm'), ('µg', 'Microgramm'), ('g', 'Gramm'), ('IE', 'Intern. Einheiten')], max_length=2, verbose_name='Einheit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Medikament',
                'verbose_name_plural': 'Medikamente',
                'ordering': ['name', 'strength'],
            },
        ),
        migrations.CreateModel(
            name='StockChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Menge')),
                ('reason', models.CharField(choices=[('', 'wählen ...'), ('01', 'Neue Packung (+)'), ('02', 'Einnahme vergessen (+)'), ('03', 'Einnahme ausgesetzt (+)'), ('04', 'Verfallsdatum erreicht (-)'), ('05', 'Dosis erhöht (-)'), ('98', 'Sonstiges (+)'), ('99', 'Sonstiges (-)')], max_length=2, verbose_name='Grund')),
                ('text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anmerkung')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicament.medicament', verbose_name='Medikament')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Stock change',
                'verbose_name_plural': 'Stock changes',
            },
        ),
    ]
