# Generated by Django 4.0.6 on 2022-07-22 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Eigentümer'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='package',
            field=models.PositiveIntegerField(help_text='Tablets', verbose_name='Packungsgröße'),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Eigentümer'),
        ),
    ]
