# Generated by Django 4.0.6 on 2022-07-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0002_alter_medicament_owner_alter_medicament_package_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicament',
            options={'ordering': ['name', 'strength'], 'verbose_name': 'Medicament', 'verbose_name_plural': 'Medikamente'},
        ),
        migrations.AlterModelOptions(
            name='stockchange',
            options={'verbose_name': 'Bestandsveränderung', 'verbose_name_plural': 'Bestandsveränderungen'},
        ),
        migrations.AlterField(
            model_name='medicament',
            name='package',
            field=models.PositiveIntegerField(help_text='Tablette(n)', verbose_name='Packungsgröße'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='producer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='strength',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Stärke'),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicament.medicament', verbose_name='Medicament'),
        ),
    ]
