# Generated by Django 4.0.6 on 2022-07-29 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0003_alter_medicament_options_alter_stockchange_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicament',
            options={'ordering': ['name', 'strength'], 'verbose_name': 'Medikament', 'verbose_name_plural': 'Medikamente'},
        ),
        migrations.AlterModelOptions(
            name='stockchange',
            options={'verbose_name': 'Stock change', 'verbose_name_plural': 'Stock changes'},
        ),
        migrations.AlterField(
            model_name='medicament',
            name='package',
            field=models.PositiveIntegerField(help_text='Tablets', verbose_name='Packungsgröße'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='producer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Producer'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='strength',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Strength'),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicament.medicament', verbose_name='Medikament'),
        ),
    ]
