# Generated by Django 4.0.6 on 2022-08-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0004_alter_medicament_options_alter_stockchange_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Stock'),
        ),
    ]
