# Generated by Django 4.0.6 on 2022-08-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0006_alter_stockchange_options_alter_stockchange_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockchange',
            name='reason',
            field=models.CharField(choices=[('00', 'Consumption (-)'), ('01', 'Neue Packung (+)'), ('02', 'Einnahme vergessen (+)'), ('03', 'Einnahme ausgesetzt (+)'), ('04', 'Verfallsdatum erreicht (-)'), ('05', 'Dosis erhöht (-)'), ('98', 'Sonstiges (+)'), ('99', 'Sonstiges (-)')], max_length=2, verbose_name='Grund'),
        ),
    ]
