# Generated by Django 4.1 on 2022-08-11 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0008_alter_medicament_options_alter_stockchange_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicament',
            options={'ordering': ['name', 'strength'], 'verbose_name': 'Medikament', 'verbose_name_plural': 'Medikamente'},
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicament.medicament', verbose_name='Medikament'),
        ),
    ]
