# Generated by Django 4.2 on 2023-04-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0009_alter_medicament_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=3, verbose_name='Key')),
                ('short', models.CharField(max_length=20, verbose_name='Short name')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Dosage form',
                'verbose_name_plural': 'Dosage forms',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='MedPznData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pzn', models.PositiveIntegerField(db_index=True, verbose_name='PZN')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('producer', models.CharField(max_length=50, verbose_name='Hersteller')),
                ('ref_date', models.DateField(verbose_name='Reference date')),
                ('verification', models.CharField(max_length=10)),
                ('dosage_form', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medicament.dosageform')),
            ],
            options={
                'verbose_name': 'PZN Data',
                'ordering': ['pzn'],
            },
        ),
    ]
