# Generated by Django 4.2 on 2023-04-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0010_dosageform_medpzndata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosageform',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
