# Generated by Django 4.2 on 2023-04-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0011_alter_dosageform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medpzndata',
            name='producer',
            field=models.CharField(max_length=100, verbose_name='Hersteller'),
        ),
    ]
