# Generated by Django 4.2 on 2023-04-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0012_alter_medpzndata_producer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosageform',
            options={'ordering': ['key'], 'verbose_name': 'Darreichungsform', 'verbose_name_plural': 'Darreichungsformen'},
        ),
        migrations.AlterModelOptions(
            name='medpzndata',
            options={'ordering': ['pzn'], 'verbose_name': 'PZN Nr.'},
        ),
        migrations.AlterField(
            model_name='dosageform',
            name='key',
            field=models.CharField(db_index=True, max_length=3, verbose_name='Schlüssel'),
        ),
        migrations.AlterField(
            model_name='dosageform',
            name='short',
            field=models.CharField(max_length=20, verbose_name='Kurzname'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='last_calc',
            field=models.DateField(null=True, verbose_name='Letzte Bestandsberechnung'),
        ),
        migrations.AlterField(
            model_name='medpzndata',
            name='dosage_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medicament.dosageform', verbose_name='Darreichungsform'),
        ),
        migrations.AlterField(
            model_name='medpzndata',
            name='ref_date',
            field=models.DateField(verbose_name='Referenz-Datum'),
        ),
        migrations.AlterField(
            model_name='medpzndata',
            name='verification',
            field=models.CharField(max_length=10, verbose_name='Verifikation'),
        ),
        migrations.AlterField(
            model_name='stockchange',
            name='reason',
            field=models.CharField(choices=[('00', 'Verbrauch (-)'), ('01', 'Neue Packung (+)'), ('02', 'Einnahme vergessen (+)'), ('03', 'Einnahme ausgesetzt (+)'), ('04', 'Vallsdatum erreicht (-)'), ('05', 'Dosis erhöht (-)'), ('98', 'Sonstiges (+)'), ('99', 'Sonstiges (-)')], max_length=2, verbose_name='Grund'),
        ),
    ]
