# Generated by Django 4.2 on 2023-04-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0013_alter_dosageform_options_alter_medpzndata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='pzn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicament.medpzndata', verbose_name='PZN Nr.'),
        ),
    ]
