# Generated by Django 6.0.5 on 2026-06-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0014_medicament_pzn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='pzn',
        ),
        migrations.DeleteModel(
            name='MedPznData',
        ),
    ]
