# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestandsveraenderung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Datum')),
                ('menge', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Menge')),
                ('grund', models.CharField(choices=[('', 'w\xe4hlen...'), ('01', 'Neue Packung (+)'), ('02', 'Einnhame vergessen (+)'), ('03', 'Einnahme ausgesetzt (+)'), ('04', 'Verfallsdatum erreicht (-)'), ('05', 'Dosis erh\xf6ht (-)'), ('98', 'Sonstige Korrektur (+)'), ('99', 'Sonstige Korrektur (-)')], max_length=2, verbose_name='Einheit')),
                ('text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anmerkung')),
            ],
            options={
                'verbose_name': 'Bestandsver\xe4nderung',
                'verbose_name_plural': 'Bestandsver\xe4nderungen',
            },
        ),
        migrations.CreateModel(
            name='Medikament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('hersteller', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hersteller')),
                ('wirkstoff', models.CharField(blank=True, max_length=50, null=True, verbose_name='Wirkstoff')),
                ('packung', models.IntegerField(help_text=' Tabletten', verbose_name='Packungsgr\xf6\xdfe')),
                ('staerke', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dosis')),
                ('einheit', models.CharField(choices=[('mg', 'Milligramm'), ('\xb5g', 'Microgramm'), ('g', 'Gramm'), ('IE', 'Intern. Einheiten')], max_length=2, verbose_name='Einheit')),
                ('bestand', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Bestand')),
                ('bestand_vom', models.DateField(auto_now_add=True, verbose_name='Bestands\xe4nderung vom')),
                ('ref_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'staerke'],
                'verbose_name': 'Medikament',
                'verbose_name_plural': 'Medikamente',
            },
        ),
        migrations.CreateModel(
            name='Verordnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morgen', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Morgen')),
                ('mittag', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Mittag')),
                ('abend', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Abend')),
                ('nacht', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Nacht')),
                ('mo', models.BooleanField(default=False, verbose_name='Mo')),
                ('di', models.BooleanField(default=False, verbose_name='Di')),
                ('mi', models.BooleanField(default=False, verbose_name='Mi')),
                ('do', models.BooleanField(default=False, verbose_name='Do')),
                ('fr', models.BooleanField(default=False, verbose_name='Fr')),
                ('sa', models.BooleanField(default=False, verbose_name='Sa')),
                ('so', models.BooleanField(default=False, verbose_name='So')),
                ('ref_medikament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medikamente.Medicament', verbose_name='Medikament')),
                ('ref_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Verordnung',
                'verbose_name_plural': 'Verordnungen',
            },
        ),
        migrations.CreateModel(
            name='VrdFuture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morgen', models.DecimalField(blank=True, decimal_places=2, help_text=' Tabl.', max_digits=3, null=True, verbose_name='Morgen')),
                ('mittag', models.DecimalField(blank=True, decimal_places=2, help_text=' Tabl.', max_digits=3, null=True, verbose_name='Mittag')),
                ('abend', models.DecimalField(blank=True, decimal_places=2, help_text=' Tabl.', max_digits=3, null=True, verbose_name='Abend')),
                ('nacht', models.DecimalField(blank=True, decimal_places=2, help_text=' Tabl.', max_digits=3, null=True, verbose_name='Nacht')),
                ('mo', models.BooleanField(default=False, verbose_name='Mo')),
                ('di', models.BooleanField(default=False, verbose_name='Di')),
                ('mi', models.BooleanField(default=False, verbose_name='Mi')),
                ('do', models.BooleanField(default=False, verbose_name='Do')),
                ('fr', models.BooleanField(default=False, verbose_name='Fr')),
                ('sa', models.BooleanField(default=False, verbose_name='Sa')),
                ('so', models.BooleanField(default=False, verbose_name='So')),
                ('gueltig_ab', models.DateField(verbose_name='g\xfcltig ab')),
                ('erledigt', models.BooleanField(default=False, verbose_name='erledigt')),
                ('ref_medikament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medikamente.Medicament', verbose_name='Medikament')),
                ('ref_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Terminierte Verordnung',
                'verbose_name_plural': 'Terminierte Verordnungen',
            },
        ),
        migrations.AddField(
            model_name='bestandsveraenderung',
            name='ref_medikament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medikamente.Medicament'),
        ),
        migrations.AddField(
            model_name='bestandsveraenderung',
            name='ref_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
