# Generated by Django 2.2 on 2019-04-23 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medikamente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestandsveraenderung',
            name='ref_medikament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medikamente.Medikament'),
        ),
        migrations.AlterField(
            model_name='bestandsveraenderung',
            name='ref_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medikament',
            name='ref_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='ref_medikament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medikamente.Medikament', verbose_name='Medikament'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='ref_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='vrdfuture',
            name='ref_medikament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medikamente.Medikament', verbose_name='Medikament'),
        ),
        migrations.AlterField(
            model_name='vrdfuture',
            name='ref_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
    ]
