# Generated by Django 2.2 on 2019-04-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medikamente', '0002_auto_20190423_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medikament',
            name='packung',
            field=models.PositiveIntegerField(help_text=' Tabletten', verbose_name='Packungsgröße'),
        ),
    ]
