# Generated by Django 2.2 on 2019-04-25 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medikamente', '0003_auto_20190424_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestandsveraenderung',
            options={'verbose_name': 'Change of inventory', 'verbose_name_plural': 'Changes of inventory'},
        ),
        migrations.AlterModelOptions(
            name='medikament',
            options={'ordering': ['name', 'staerke'], 'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicine'},
        ),
        migrations.AlterModelOptions(
            name='verordnung',
            options={'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
        migrations.AlterModelOptions(
            name='vrdfuture',
            options={'verbose_name': 'Scheduled medication', 'verbose_name_plural': 'Scheduled medications'},
        ),
        migrations.AlterField(
            model_name='bestandsveraenderung',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bestandsveraenderung',
            name='grund',
            field=models.CharField(choices=[('', 'choose ...'), ('01', 'New Package (+)'), ('02', 'Intake missed (+)'), ('03', 'Intake skipped (+)'), ('04', 'Expiry date reached (-)'), ('05', 'Dose increased (-)'), ('98', 'Other (+)'), ('99', 'Other (-)')], max_length=2, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='bestandsveraenderung',
            name='menge',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='bestandsveraenderung',
            name='ref_medikament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medikamente.Medicament', verbose_name='Medicine'),
        ),
        migrations.AlterField(
            model_name='bestandsveraenderung',
            name='ref_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='bestandsveraenderung',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='medikament',
            name='bestand',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Inventory'),
        ),
        migrations.AlterField(
            model_name='medikament',
            name='bestand_vom',
            field=models.DateField(auto_now_add=True, verbose_name='Inventory change'),
        ),
        migrations.AlterField(
            model_name='medikament',
            name='einheit',
            field=models.CharField(choices=[('mg', 'Milligram'), ('µg', 'Microgram'), ('g', 'Gram'), ('IE', 'Intern. units')], max_length=2, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='medikament',
            name='hersteller',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='medikament',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Denomination'),
        ),
        migrations.AlterField(
            model_name='medikament',
            name='packung',
            field=models.PositiveIntegerField(help_text=' Tablets', verbose_name='Package size'),
        ),
        migrations.AlterField(
            model_name='medikament',
            name='staerke',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dose'),
        ),
        migrations.AlterField(
            model_name='medikament',
            name='wirkstoff',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Active ingredient'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='abend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Evening'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='di',
            field=models.BooleanField(default=False, verbose_name='Tu'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='do',
            field=models.BooleanField(default=False, verbose_name='Th'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='mi',
            field=models.BooleanField(default=False, verbose_name='We'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='mittag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Noon'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='morgen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Morning'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='nacht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Night'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='ref_medikament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medikamente.Medicament', verbose_name='Medication'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='so',
            field=models.BooleanField(default=False, verbose_name='Su'),
        ),
    ]
