# Generated by Django 3.1.7 on 2021-03-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medikamente', '0005_auto_20190426_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verordnung',
            name='di',
            field=models.BooleanField(default=True, verbose_name='Tu'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='do',
            field=models.BooleanField(default=True, verbose_name='Th'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='fr',
            field=models.BooleanField(default=True, verbose_name='Fr'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='mi',
            field=models.BooleanField(default=True, verbose_name='We'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='mo',
            field=models.BooleanField(default=True, verbose_name='Mo'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='sa',
            field=models.BooleanField(default=True, verbose_name='Sa'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='so',
            field=models.BooleanField(default=True, verbose_name='Su'),
        ),
    ]
