# Generated by Django 3.2.10 on 2021-12-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medikamente', '0006_auto_20210322_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verordnung',
            options={'ordering': ['ref_medikament__name', 'ref_medikament__staerke'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
    ]
