# Generated by Django 4.0.6 on 2022-07-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medikamente', '0007_alter_verordnung_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='verordnung',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Valid from'),
        ),
        migrations.AddField(
            model_name='verordnung',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Valid until'),
        ),
        migrations.AlterField(
            model_name='verordnung',
            name='ref_medikament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medikamente.medikament', verbose_name='Medicament'),
        ),
    ]
