# Generated by Django 4.0.6 on 2022-07-22 06:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medikamente', '0008_verordnung_valid_from_verordnung_valid_until_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bestandsveraenderung',
            new_name='StockChange',
        ),
    ]
