# Generated by Django 4.0.6 on 2022-07-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medikamente', '0009_rename_bestandsveraenderung_stockchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockchange',
            old_name='menge',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='stockchange',
            old_name='ref_medikament',
            new_name='medicament',
        ),
        migrations.RemoveField(
            model_name='stockchange',
            name='grund',
        ),
        migrations.AddField(
            model_name='stockchange',
            name='reason',
            field=models.CharField(choices=[('', 'choose ...'), ('01', 'New Package (+)'), ('02', 'Intake missed (+)'), ('03', 'Intake skipped (+)'), ('04', 'Expiry date reached (-)'), ('05', 'Dose increased (-)'), ('98', 'Other (+)'), ('99', 'Other (-)')], default='01', max_length=2, verbose_name='Reason'),
            preserve_default=False,
        ),
    ]
