# Generated by Django 4.0.6 on 2022-07-22 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medikamente', '0010_rename_menge_stockchange_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verordnung',
            new_name='Prescription',
        ),
    ]
