# Generated by Django 4.0.6 on 2022-07-22 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medikamente', '0011_rename_verordnung_prescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medikament',
            new_name='Medicament',
        ),
        migrations.AlterField(
            model_name='vrdfuture',
            name='ref_medikament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medikamente.Medicament', verbose_name='Medicament'),
        ),
    ]
