# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 16:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.CharField(max_length=100, verbose_name='URL-Pattern')),
            ],
            options={
                'verbose_name': 'Startseite',
                'verbose_name_plural': 'Startseiten',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gebdat', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('warnenTageVorher', models.IntegerField(default=20, help_text='Tage', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)], verbose_name='Medikamente vorhalten f\xfcr mindestens')),
                ('werteLetzteTage', models.IntegerField(default=30, help_text='Tage', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(365)], verbose_name='Standart Zeitraum Messwerte anzeigen')),
                ('zeigeArztWerte', models.BooleanField(default=False, verbose_name='Arzt darf Messwerte sehen')),
                ('zeigeArztMed', models.BooleanField(default=False, verbose_name='Arzt darf Medikamente sehen')),
                ('email_arzt', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email-Adresse Arzt')),
                ('myStartPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usrprofile.StartUrl', verbose_name='Meine Startseite')),
                ('ref_usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Einstellung',
                'verbose_name_plural': 'Einstellungen',
            },
        ),
    ]
