# Generated by Django 2.2 on 2019-04-24 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usrprofile', '0002_auto_20190423_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starturl',
            options={'verbose_name': 'Home page', 'verbose_name_plural': 'Home pages'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User setting', 'verbose_name_plural': 'User settings'},
        ),
        migrations.AlterField(
            model_name='starturl',
            name='url',
            field=models.CharField(max_length=100, verbose_name='URL pattern'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_arzt',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Doctor's email address"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gebdat',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='myStartPage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usrprofile.StartUrl', verbose_name='My home page'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ref_usr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='warnenTageVorher',
            field=models.IntegerField(default=20, help_text='days', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)], verbose_name='Hold medications for at least'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='werteLetzteTage',
            field=models.IntegerField(default=30, help_text='days', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(365)], verbose_name='Show readings for'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zeigeArztMed',
            field=models.BooleanField(default=False, verbose_name='Doctor is allowed to see medications'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zeigeArztWerte',
            field=models.BooleanField(default=False, verbose_name='Doctor is allowed to see readings'),
        ),
    ]
