# Generated by Django 2.2 on 2019-04-26 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrprofile', '0003_auto_20190424_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='warnenTageVorher',
            field=models.IntegerField(default=20, help_text='days', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)], verbose_name='Hold medicaments inventory for at least'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zeigeArztMed',
            field=models.BooleanField(default=False, verbose_name='Doctor is allowed to see prescription'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zeigeArztWerte',
            field=models.BooleanField(default=False, verbose_name='Doctor is allowed to see measurements'),
        ),
    ]
