# Generated by Django 4.0.2 on 2022-02-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrprofile', '0004_auto_20190426_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starturl',
            options={'ordering': ['sort_order'], 'verbose_name': 'Home page', 'verbose_name_plural': 'Home pages'},
        ),
        migrations.AlterField(
            model_name='starturl',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
