# Generated by Django 4.0.6 on 2022-07-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrprofile', '0005_alter_starturl_options_alter_starturl_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='measurements_items_per_page',
            field=models.PositiveSmallIntegerField(default=16, verbose_name='Items per page'),
        ),
    ]
