# Generated by Django 4.0.6 on 2022-07-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrprofile', '0006_userprofile_measurements_items_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='medicaments_items_per_page',
            field=models.PositiveSmallIntegerField(default=16, verbose_name='Items per page'),
        ),
    ]
