# Generated by Django 4.1 on 2022-08-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrprofile', '0007_userprofile_medicaments_items_per_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='myStartPage',
            new_name='my_start_page',
        ),
    ]
