# Generated by Django 4.1 on 2022-08-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrprofile', '0008_rename_mystartpage_userprofile_my_start_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='warnenTageVorher',
            new_name='warn_days_before',
        ),
    ]
