# Generated by Django 4.1 on 2022-08-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrprofile', '0009_rename_warnentagevorher_userprofile_warn_days_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='werteLetzteTage',
            new_name='show_measurement_days',
        ),
    ]
