# Generated by Django 4.1 on 2022-08-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrprofile', '0010_rename_werteletztetage_userprofile_show_measurement_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='zeigeArztWerte',
            new_name='doc_can_see_msm',
        ),
    ]
