# Generated by Django 4.1 on 2022-08-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrprofile', '0011_rename_zeigearztwerte_userprofile_doc_can_see_msm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='zeigeArztMed',
            new_name='doc_can_see_med',
        ),
    ]
