# Generated by Django 5.1.3 on 2024-11-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0013_remove_valuetype_active_remove_valuetype_owner'),
        ('usrprofile', '0012_rename_zeigearztmed_userprofile_doc_can_see_med'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_value_types',
            field=models.ManyToManyField(blank=True, to='measurement.valuetype', verbose_name='Active types'),
        ),
    ]
