# Generated by Django 4.0.6 on 2022-07-22 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Morgen')),
                ('noon', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Mittag')),
                ('evening', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Abend')),
                ('night', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Nacht')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid from')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid until')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medicament.medicament', verbose_name='Medikament')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Verordnung',
                'verbose_name_plural': 'Verordnungen',
                'ordering': ['medicament__name', 'medicament__strength'],
            },
        ),
    ]
