# Generated by Django 4.0.6 on 2022-07-22 16:03

from django.db import migrations, models
import django.db.models.deletion
import prescription.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0002_alter_medicament_owner_alter_medicament_package_and_more'),
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['medicament__name', 'medicament__strength'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AddField(
            model_name='prescription',
            name='weekdays',
            field=models.JSONField(blank=True, verbose_name='Weekdays'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='evening',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Evening'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medicament.medicament', verbose_name='Medicament'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='morning',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Morning'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Night'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='noon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Noon'),
        ),
    ]
