# Generated by Django 4.0.6 on 2022-08-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_alter_prescription_options_prescription_weekdays_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='weekdays',
            new_name='old_weekdays',
        ),
    ]
