# Generated by Django 4.0.6 on 2022-08-05 11:52

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_rename_weekdays_prescription_old_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='weekdays',
            field=bitfield.models.BitField(('mo', 'tu', 'we', 'th', 'fr', 'sa', 'su'), default=0),
        ),
    ]
