# Generated by Django 4.0.6 on 2022-08-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_prescription_weekdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='old_weekdays',
        ),
    ]
