# Generated by Django 4.0.6 on 2022-08-08 05:30

from django.db import migrations


def set_values(apps, schema_editor):
    prescription_model = apps.get_model('prescription', 'prescription')
    for prs in prescription_model.objects.all():
        if prs.morning is None:
            prs.morning = 0.0
        if prs.noon is None:
            prs.noon = 0.0
        if prs.evening is None:
            prs.evening = 0.0
        if prs.night is None:
            prs.night = 0.0
        prs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_remove_prescription_old_weekdays'),
    ]

    operations = [
        migrations.RunPython(set_values)
    ]
