# Generated by Django 4.0.6 on 2022-08-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_set_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='evening',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Evening'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='morning',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Morning'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='night',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Night'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='noon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Noon'),
        ),
    ]
