# Generated by Django 4.1.1 on 2022-09-23 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescription', '0007_alter_prescription_evening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
