# Generated by Django 5.0.7 on 2024-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0008_alter_prescription_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='evening',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True, verbose_name='Evening'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='morning',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True, verbose_name='Morning'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='night',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True, verbose_name='Night'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='noon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True, verbose_name='Noon'),
        ),
    ]
