# Generated by Django 2.2 on 2019-04-23 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('werte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wert',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='wert',
            name='ref_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
