# Generated by Django 2.2 on 2019-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werte', '0002_auto_20190423_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wert',
            options={'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
        migrations.AlterField(
            model_name='wert',
            name='bemerkung',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Peculiarity'),
        ),
        migrations.AlterField(
            model_name='wert',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='wert',
            name='gew',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='wert',
            name='puls',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Pulse'),
        ),
        migrations.AlterField(
            model_name='wert',
            name='rrdia',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='RR dia'),
        ),
        migrations.AlterField(
            model_name='wert',
            name='rrsys',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='RR sys'),
        ),
        migrations.AlterField(
            model_name='wert',
            name='temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Temp.'),
        ),
    ]
