# Generated by Django 2.2 on 2019-04-23 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('werte', '0002_auto_20190423_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wert',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='wert',
            name='ref_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
