# Generated by Django 4.0.6 on 2022-07-14 20:13

from django.db import migrations


def migrate_werte(apps, schema_editor):
    wert_model = apps.get_model('werte', 'wert')
    value_model = apps.get_model('werte', 'value')
    value_type_model = apps.get_model('werte', 'valuetype')
    measurement_model = apps.get_model('werte', 'measurement')

    rrsys, created = value_type_model.objects.get_or_create(
        name='RR sys',
        slug='rrsys',
        unit='mm/HG',
    )
    rrdia, created = value_type_model.objects.get_or_create(
        name='RR dia',
        slug='rrdia',
        unit='mm/HG',
    )
    puls, created = value_type_model.objects.get_or_create(
        name='Puls',
        slug='puls',
        unit='1/min',
    )
    temp, created = value_type_model.objects.get_or_create(
        name='Temp.',
        slug='temp',
        unit='°C',
    )
    gew, created = value_type_model.objects.get_or_create(
        name='Gewicht',
        slug='gewicht',
        unit='Kg',
    )

    for wert in wert_model.objects.all():
        measurement = measurement_model.objects.create(
            owner=wert.ref_usr,
            comment=wert.bemerkung
        )
        measurement.date = wert.date
        measurement.save()

        value_model.objects.create(
            measurement=measurement,
            value_type=rrsys,
            value=wert.rrsys or None
        )
        value_model.objects.create(
            measurement=measurement,
            value_type=rrdia,
            value=wert.rrdia or None
        )
        value_model.objects.create(
            measurement=measurement,
            value_type=puls,
            value=wert.puls or None
        )
        value_model.objects.create(
            measurement=measurement,
            value_type=temp,
            value=wert.temp or None
        )
        value_model.objects.create(
            measurement=measurement,
            value_type=gew,
            value=wert.gew or None
        )


class Migration(migrations.Migration):

    dependencies = [
        ('werte', '0004_measurement_valuetype_value'),
    ]

    operations = [
        migrations.RunPython(migrate_werte)
    ]
