# Generated by Django 4.0.6 on 2022-07-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werte', '0004_measurement_valuetype_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuetype',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
