# Generated by Django 4.0.6 on 2022-07-14 20:13

from django.db import migrations


def migrate_werte(apps, schema_editor):
    wert_model = apps.get_model('werte', 'wert')
    value_model = apps.get_model('werte', 'value')
    value_type_model = apps.get_model('werte', 'valuetype')
    measurement_model = apps.get_model('werte', 'measurement')

    rrsys = value_type_model.objects.get(slug='rrsys')
    rrdia = value_type_model.objects.get(slug='rrdia')
    puls = value_type_model.objects.get(slug='puls')
    temp = value_type_model.objects.get(slug='temp')
    gew = value_type_model.objects.get(slug='gewicht')

    for wert in wert_model.objects.all():
        measurement = measurement_model.objects.create(
            owner=wert.ref_usr,
            comment=wert.bemerkung
        )
        measurement.date = wert.date
        measurement.save()

        value_model.objects.create(
            measurement=measurement,
            value_type=rrsys,
            value=wert.rrsys or None
        )
        value_model.objects.create(
            measurement=measurement,
            value_type=rrdia,
            value=wert.rrdia or None
        )
        value_model.objects.create(
            measurement=measurement,
            value_type=puls,
            value=wert.puls or None
        )
        value_model.objects.create(
            measurement=measurement,
            value_type=temp,
            value=wert.temp or None
        )
        value_model.objects.create(
            measurement=measurement,
            value_type=gew,
            value=wert.gew or None
        )


class Migration(migrations.Migration):

    dependencies = [
        ('werte', '0005_valuetype_slug'),
    ]

    operations = [
        migrations.RunPython(migrate_werte)
    ]
