# Generated by Django 4.0.6 on 2022-07-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werte', '0006_auto_20220714_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valuetype',
            options={'ordering': ['sort_order'], 'verbose_name': 'Value Type', 'verbose_name_plural': 'Value Types'},
        ),
        migrations.AddField(
            model_name='valuetype',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
