# Generated by Django 4.0.6 on 2022-07-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werte', '0008_valuetype_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-date'], 'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
    ]
