# Generated by Django 4.0.6 on 2022-07-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werte', '0009_alter_measurement_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuetype',
            name='format',
        ),
    ]
