
# Generated by Django 1.11.8 on 2018-02-27 16:25
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Datum')),
                ('rrsys', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='RR-Sys')),
                ('rrdia', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='RR-Dia')),
                ('puls', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Puls')),
                ('temp', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Temp')),
                ('gew', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Gewicht')),
                ('bemerkung', models.CharField(blank=True, max_length=50, null=True, verbose_name='Besonderheiten')),
                ('ref_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messwert',
                'verbose_name_plural': 'Messwerte',
            },
        ),
    ]
