# Generated by Django 4.0.6 on 2022-07-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_auto_20220714_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valuetype',
            options={'ordering': ['sort_order'], 'verbose_name': 'Value Type', 'verbose_name_plural': 'Value Types'},
        ),
        migrations.AlterField(
            model_name='valuetype',
            name='slug',
            field=models.SlugField(),
        ),
    ]
