# Generated by Django 4.0.6 on 2022-07-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_remove_valuetype_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuetype',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
