# Generated by Django 4.1 on 2022-08-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0011_alter_valuetype_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wert',
        ),
    ]
