# Generated by Django 5.1.3 on 2024-11-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0012_delete_wert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuetype',
            name='active',
        ),
        migrations.RemoveField(
            model_name='valuetype',
            name='owner',
        ),
    ]
