name: Format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Check format
        run: pylint --recursive=y .

